# Generated by Django 4.1.5 on 2023-01-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=500)),
                ('s_level', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500)),
                ('r_email', models.CharField(max_length=500)),
                ('r_phone', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('lname', models.CharField(max_length=500)),
                ('mname', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('dob', models.DateField(default='None')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(default='profile/avator.png', null=True, upload_to='profile/')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_office', models.CharField(max_length=500)),
                ('e_position', models.CharField(max_length=500)),
                ('e_duration', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_institution', models.CharField(max_length=500)),
                ('a_year', models.CharField(max_length=500)),
                ('a_award', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.cv')),
            ],
        ),
    ]
